/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cybex_gma_client_ui_JNIUtil */

#ifndef _Included_com_cybex_gma_client_ui_JNIUtil
#define _Included_com_cybex_gma_client_ui_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cybex_gma_client_ui_JNIUtil
 * Method:    createKey
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_cybex_gma_client_ui_JNIUtil_createKey
  (JNIEnv *, jclass);

/*
 * Class:     com_cybex_gma_client_ui_JNIUtil
 * Method:    get_cypher
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cybex_gma_client_ui_JNIUtil_get_1cypher
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_cybex_gma_client_ui_JNIUtil
 * Method:    get_private_key
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cybex_gma_client_ui_JNIUtil_get_1private_1key
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
